# Generated by Django 3.2.3 on 2021-06-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formulario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='run')),
                ('nombreCompleto', models.CharField(max_length=100, verbose_name='name_completo')),
                ('correo_electronico', models.EmailField(max_length=100, verbose_name='correo_e')),
                ('numero', models.IntegerField(verbose_name='numero_telefonico')),
                ('mensaje', models.TextField(max_length=300, verbose_name='mensaje_dejado')),
            ],
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('idRegistro', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_registro')),
                ('nombres', models.CharField(max_length=50, verbose_name='nombre_completo')),
                ('apellidos', models.CharField(max_length=50, verbose_name='apellido_completo')),
                ('usuario', models.CharField(max_length=60, verbose_name='nombre_usuario')),
                ('correo', models.EmailField(max_length=100, verbose_name='correo')),
                ('contraseña', models.CharField(max_length=50, verbose_name='contraseña')),
            ],
        ),
    ]
