# Generated by Django 3.2.3 on 2021-06-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registro_idregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='listadoTortas',
            fields=[
                ('idtorta', models.AutoField(primary_key=True, serialize=False, verbose_name='id_torta')),
                ('torta', models.CharField(max_length=50, verbose_name='nombre torta')),
                ('tipotorta', models.CharField(max_length=50, verbose_name='tipo torta')),
                ('tamaño', models.CharField(max_length=50, verbose_name='tamaño torta')),
                ('stock', models.IntegerField(verbose_name='cantidad tortas')),
            ],
        ),
    ]
