# Generated by Django 3.2.3 on 2021-06-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_listadotortas'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadotortas',
            name='foto',
            field=models.ImageField(default='/static/core/sin_imagen.jpg', null=True, upload_to='', verbose_name='foto tortas'),
        ),
    ]
