# Generated by Django 3.2.3 on 2021-06-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_listadotortas_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadotortas',
            name='foto',
            field=models.ImageField(null=True, upload_to='core', verbose_name='foto tortas'),
        ),
    ]
