# Generated by Django 3.2.3 on 2021-06-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_listadotortas_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listadotortas',
            old_name='tamaño',
            new_name='tamanio',
        ),
    ]
