# Generated by Django 3.2.3 on 2021-06-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_tamaño_listadotortas_tamanio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadotortas',
            name='foto',
            field=models.ImageField(default='static/core/img/sin_imagen.jpg', upload_to='core', verbose_name='foto tortas'),
        ),
    ]
