# Generated by Django 3.2.3 on 2021-06-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_listadotortas_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('idboleta', models.AutoField(primary_key=True, serialize=False, verbose_name='id_ventas')),
                ('nombreventa', models.CharField(max_length=50, verbose_name='venta')),
            ],
        ),
    ]
